AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster with Managed Node Group

Resources:

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Join ['-', ['eks-cluster', !Ref 'AWS::StackName', !Ref 'AWS::Region']]
      RoleArn: !ImportValue "MyStack-EKSClusterRoleArn"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !ImportValue "MyStack-EKSSecurityGroupId"
        SubnetIds:
          - !ImportValue "MyStack-PublicSubnet1"
          - !ImportValue "MyStack-PublicSubnet2"
          - !ImportValue "MyStack-PrivateSubnet1"
          - !ImportValue "MyStack-PrivateSubnet2"

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodeRole: !ImportValue "MyStack-EKSNodeRoleArn"
      Subnets:
        - !ImportValue "MyStack-PrivateSubnet1"
        - !ImportValue "MyStack-PrivateSubnet2"
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 3
        MinSize: 1
      InstanceTypes:
        - t3.medium

Outputs:
  ClusterName:
    Value: !GetAtt EKSCluster.Name
  ClusterArn:
    Value: !GetAtt EKSCluster.Arn
