AWSTemplateFormatVersion: "2010-09-09"
Description: "Simplified RDS PostgreSQL instance for demo environment"

Parameters:
  ClusterName:
    Type: String
    Default: demo-eks
    Description: Name of the EKS cluster for resource tagging

Resources:
  # Generate a random password for the RDS instance
  DBPasswordSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: !Sub "${ClusterName}-demo-db-password"
      Description: "Password for RDS PostgreSQL instance"
      GenerateSecretString:
        SecretStringTemplate: '{\"username\": \"postgres\"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '\"@/\\'
      Tags:
        - Key: Name
          Value: !Sub "${ClusterName}-demo-db-password"
        - Key: Environment
          Value: demo
        - Key: ManagedBy
          Value: CloudFormation

  # Store the password in SSM Parameter Store
  DBPasswordParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/database/${ClusterName}/demo/password"
      Description: "Password for RDS PostgreSQL instance"
      Type: "SecureString"
      Value: !Join ['', ['{{resolve:secretsmanager:', !Ref DBPasswordSecret, ':SecretString:password}}' ]]
      Tags:
        Environment: demo
        ManagedBy: CloudFormation
        ClusterName: !Ref ClusterName

  # DB Subnet Group using the private subnet from the VPC stack
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for PostgreSQL RDS instance"
      SubnetIds:
        - Fn::ImportValue: !Sub "${ClusterName}-PrivateSubnet1"
        - Fn::ImportValue: !Sub "${ClusterName}-PublicSubnet1"  # Using public subnet as second subnet for demo
      Tags:
        - Key: Name
          Value: !Sub "${ClusterName}-demo-db-subnet-group"
        - Key: Environment
          Value: demo
        - Key: ManagedBy
          Value: CloudFormation

  # PostgreSQL RDS Instance - Simplified for demo
  PostgreSQLInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${ClusterName}-demo-postgres"
      DBName: "appdb"
      Engine: postgres
      EngineVersion: "17.5"
      DBInstanceClass: "db.t3.micro"  # Smaller instance for demo
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: "postgres"
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBPasswordSecret, ':SecretString:password}}' ]]
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${ClusterName}-PrivateSecurityGroupId"
      BackupRetentionPeriod: 1  # Reduced for demo
      MultiAZ: false  # Disabled for demo
      PubliclyAccessible: false
      StorageEncrypted: true
      DeletionProtection: false  # Disabled for demo
      Tags:
        - Key: Name
          Value: !Sub "${ClusterName}-demo-postgres"
        - Key: Environment
          Value: demo
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  DBInstanceIdentifier:
    Description: "The identifier for the RDS instance"
    Value: !Ref PostgreSQLInstance
    Export:
      Name: !Sub "${ClusterName}-DBInstanceIdentifier"
      
  DBInstanceEndpoint:
    Description: "The connection endpoint for the PostgreSQL instance"
    Value: !GetAtt PostgreSQLInstance.Endpoint.Address
    Export:
      Name: !Sub "${ClusterName}-DBEndpoint"
  
  DBInstancePort:
    Description: "The port for the PostgreSQL instance"
    Value: !GetAtt PostgreSQLInstance.Endpoint.Port
    Export:
      Name: !Sub "${ClusterName}-DBPort"

  DBName:
    Description: "The name of the database"
    Value: "appdb"
    Export:
      Name: !Sub "${ClusterName}-DBName"
  
  DBUsername:
    Description: "The master username for the database"
    Value: "postgres"
    Export:
      Name: !Sub "${ClusterName}-DBUsername"
  
  DBPasswordParameterName:
    Description: "Name of the SSM parameter containing the database password"
    Value: !Sub "/database/${ClusterName}/demo/password"
    Export:
      Name: !Sub "${ClusterName}-DBPasswordParameterName"