AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS PostgreSQL instance with generated password stored in SSM Parameter Store"

Resources:
  # Generate a random password for the RDS instance
  DBPasswordSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "MyStack-db-password"
      Description: "Password for RDS PostgreSQL instance"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  # Store the password in SSM Parameter Store
  DBPasswordParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/database/postgres-db/password"
      Description: "Password for RDS PostgreSQL instance"
      Type: "SecureString"
      Value: !Join ['', ['{{resolve:secretsmanager:', !Ref DBPasswordSecret, ':SecretString:password}}' ]]

  # DB Subnet Group using the private subnets from the VPC stack
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for PostgreSQL RDS instance"
      SubnetIds:
        - Fn::ImportValue: "MyStack-PrivateSubnetAId"
        - Fn::ImportValue: "MyStack-PrivateSubnetBId"
      Tags:
        - Key: Name
          Value: "MyStack-db-subnet-group"

  # PostgreSQL RDS Instance
  PostgreSQLInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: "postgres-db"
      DBName: "mybd"
      Engine: postgres
      EngineVersion: "17.5"
      DBInstanceClass: "db.t3.small"
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: "postgres"
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBPasswordSecret, ':SecretString:password}}' ]]
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: "MyStack-PrivateSecurityGroupId"
      BackupRetentionPeriod: 7
      MultiAZ: true
      PubliclyAccessible: false
      StorageEncrypted: true
      DeletionProtection: true
      Tags:
        - Key: Name
          Value: "MyStack-postgres-instance"

Outputs:
  DBInstanceIdentifier:
    Description: "The identifier for the RDS instance"
    Value: "postgres-db"
    Export:
      Name: "MyStack-DBInstanceIdentifier"
      
  DBInstanceEndpoint:
    Description: "The connection endpoint for the PostgreSQL instance"
    Value: !GetAtt PostgreSQLInstance.Endpoint.Address
    Export:
      Name: "MyStack-DBEndpoint"
  
  DBInstancePort:
    Description: "The port for the PostgreSQL instance"
    Value: !GetAtt PostgreSQLInstance.Endpoint.Port
    Export:
      Name: "MyStack-DBPort"

  DBName:
    Description: "The name of the database"
    Value: "mybd"
    Export:
      Name: "MyStack-DBName"
  
  DBUsername:
    Description: "The master username for the database"
    Value: "postgres"
    Export:
      Name: "MyStack-DBUsername"
  
  DBPasswordSecretARN:
    Description: "ARN of the secret containing the database password"
    Value: !Ref DBPasswordSecret
    Export:
      Name: "MyStack-DBPasswordSecretARN"
  
  DBPasswordParameterName:
    Description: "Name of the SSM parameter containing the database password"
    Value: "/database/postgres-db/password"
    Export:
      Name: "MyStack-DBPasswordParameterName"